import './globals.css'
// import '@styles/global.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import RootStyleRegistry from './emotion';
import {HeaderResponsive} from '@components/layout/NavBar';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <RootStyleRegistry>
        <HeaderResponsive links={[{ link:"/", label:"Accueil" },{ link:"#", label:"Créer un compte" },{ link:"/registration", label:"Trouver un professionnel" },{ link:"/registration/redirect", label:"Se connecter" },{ link:"/about", label:"À propos" }]}/>
        {children}
        </RootStyleRegistry>
        </body>
    </html>
  )
}
